# Generated by Django 4.0 on 2021-12-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_extendeduser_age_extendeduser_adhaar_num_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extendeduser',
            new_name='KYC',
        ),
    ]
