# Generated by Django 3.2.8 on 2021-12-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_extendeduser_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
