# Generated by Django 3.2.8 on 2021-12-12 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20211212_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses_model',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_acc', to=settings.AUTH_USER_MODEL),
        ),
    ]
