# Generated by Django 3.2.8 on 2022-01-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20220113_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='created_on',
        ),
    ]
