# Generated by Django 3.2.8 on 2022-01-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_remove_profilefeeditem_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='status_text',
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Clothes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Dining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Electronics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Entertainment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Fruits_vegetables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Fuel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Furniture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Grocery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Liesure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Monthly_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='Transporation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
